plugins {
    id 'com.android.application'
}

android {
    namespace 'si.kclj.pregledbk'
    compileSdk 34

    signingConfigs {
        kclj {
            storeFile file("../keystore/kclj_debug.jks")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
            storeType "JKS"
        }
    }

    defaultConfig {
        applicationId "si.kclj.pregledbk"
        minSdk 26
        targetSdk 34
        versionCode 80
        versionName "1.0.80"
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.kclj
        }
        debug {
            debuggable true
            signingConfig signingConfigs.kclj
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += ['META-INF/LICENSE', 'META-INF/NOTICE']
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.aar', '*.jar'])
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.localbroadcastmanager:localbroadcastmanager:1.1.0'
}
